name: notedash
description: notetaking and productivity tool - organize and link notes spatially

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.2.0

environment:
  sdk: ^3.3.0
  flutter: ^3.3.0

dependencies:
  flutter:
    sdk: flutter
  reorderables: 0.6.0
  uuid: ^4.3.3
  collection: ^1.18.0
  convert: ^3.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  url_launcher: ^6.3.1
  url_launcher_ios: ^6.3.2
  flutter_lints: ^3.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  ios:
    true:
  image_path_android: "assets/icon_filled_ios.png"
  image_path_ios: "assets/icon_filled_ios.png"
  macos:
    generate: true
    image_path: "assets/icon_filled_ios.png"

flutter:
  uses-material-design: true
